vcl: Include SvViewDataEntry header
Fixes this build error seen in my local --disable-pch
clang build on Debian testing after

    commit 38c6bf2364a282b1f116e26a9bd4b04065bd378e
    Date:   Mon Mar 16 18:38:17 2026 +0200

        no need to store SvViewDataEntry separately

:

    In file included from /home/michi/development/git/libreoffice/vcl/source/treelist/iconview.cxx:20:
    In file included from /home/michi/development/git/libreoffice/include/vcl/filter/PngImageWriter.hxx:11:
    In file included from /home/michi/development/git/libreoffice/include/com/sun/star/uno/Reference.hxx:29:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/ostream:42:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/ostream.h:43:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/ios:46:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/ios_base.h:43:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/locale_classes.h:42:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/string:50:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_iterator.h:3117:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/debug/stl_iterator.h:32:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/debug/helper_functions.h:37:
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_pair.h:309:11: error: field has incomplete type 'SvViewDataEntry'
      309 |       _T2 second;                ///< The second member
          |           ^
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/hashtable_policy.h:449:7: note: in instantiation of template class 'std::pair<SvTreeListEntry *const, SvViewDataEntry>' requested here
      449 |       operator==(const _Node_iterator&, const _Node_iterator&) = default;
          |       ^
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/iterator_concepts.h:395:11: note: in instantiation of template class 'std::__detail::_Node_iterator<std::pair<SvTreeListEntry *const, SvViewDataEntry>, false, false>' requested here
      395 |         typename _Iter::iterator_category;
          |                  ^
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/iterator_concepts.h:395:2: note: in instantiation of requirement here
      395 |         typename _Iter::iterator_category;
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/iterator_concepts.h:394:42: note: while substituting template arguments into constraint expression here
      394 |       concept __iter_with_nested_types = requires {
          |                                          ^~~~~~~~~~
      395 |         typename _Iter::iterator_category;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      396 |         typename _Iter::value_type;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      397 |         typename _Iter::difference_type;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      398 |         typename _Iter::reference;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
      399 |       };
          |       ~
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/iterator_concepts.h:411:14: note: while checking the satisfaction of concept '__iter_with_nested_types<std::__detail::_Node_iterator<std::pair<SvTreeListEntry *const, SvViewDataEntry>, false, false>>' requested here
      411 |     requires __detail::__iter_with_nested_types<_Iterator>
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/iterator_concepts.h:411:14: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_iterator_base_types.h:180:14: note: during template argument deduction for class template partial specialization '__iterator_traits<_Iterator, void>' [with _Iterator = std::__detail::_Node_iterator<std::pair<SvTreeListEntry *const, SvViewDataEntry>, false, false>]
      180 |     : public __iterator_traits<_Iterator> { };
          |              ^
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_iterator_base_types.h:180:14: note: in instantiation of template class 'std::__iterator_traits<std::__detail::_Node_iterator<std::pair<SvTreeListEntry *const, SvViewDataEntry>, false, false>>' requested here
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/debug/safe_iterator.h:129:21: note: in instantiation of template class 'std::iterator_traits<std::__detail::_Node_iterator<std::pair<SvTreeListEntry *const, SvViewDataEntry>, false, false>>' requested here
      129 |            = typename std::iterator_traits<_Iterator>::iterator_category>
          |                            ^
    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/debug/unordered_map:108:28: note: in instantiation of default argument for '_Safe_iterator<_Base_iterator, unordered_map<SvTreeListEntry *, SvViewDataEntry>>' required here
      108 |       typedef __gnu_debug::_Safe_iterator<
          |                            ^~~~~~~~~~~~~~~
      109 |         _Base_iterator, unordered_map>                  iterator;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/include/vcl/toolkit/treelistbox.hxx:197:17: note: in instantiation of template class 'std::unordered_map<SvTreeListEntry *, SvViewDataEntry>' requested here
      197 |     SvDataTable m_DataTable; // Mapping SvTreeListEntry -> ViewData
          |                 ^
    /home/michi/development/git/libreoffice/include/vcl/toolkit/treelist.hxx:53:7: note: forward declaration of 'SvViewDataEntry'
       53 | class SvViewDataEntry;
          |       ^

Change-Id: I9a53a6949feb233314dfae479ecf132232d13cf4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201969
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>