svx: Add missing include for std::numeric_limits
Fixes this build error seen in a local Windows build after

	commit 560efd29ea285b085f100ef1dc20dd1c2461e1d8
	Date:   Tue Apr 14 07:33:47 2026 +0530

	    tdf#146619 Cleanup/Removal of headerfiles

:

	C:/Users/mwegh/DEVELO~1/git/LIBREO~1/svx/source/customshapes/EnhancedCustomShapeGeometry.cxx(27): error C2039: 'numeric_limits': is not a member of 'std'
	C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1444~1.352\Include\span(26): note: see declaration of 'std'
	C:/Users/mwegh/DEVELO~1/git/LIBREO~1/svx/source/customshapes/EnhancedCustomShapeGeometry.cxx(27): error C2275: 'sal_Int32': expected an expression instead of a type
	C:/Users/mwegh/DEVELO~1/git/LIBREO~1/svx/source/customshapes/EnhancedCustomShapeGeometry.cxx(27): error C2039: 'min': is not a member of '`global namespace''
	C:/Users/mwegh/DEVELO~1/git/LIBREO~1/svx/source/customshapes/EnhancedCustomShapeGeometry.cxx(27): error C3861: 'min': identifier not found
	C:/Users/mwegh/DEVELO~1/git/LIBREO~1/svx/source/customshapes/EnhancedCustomShapeGeometry.cxx(27): error C2737: 'MIN_INT32': const object must be initialized

Change-Id: Ie95d31530f97dbc2c8a40cb7c34fceeea7c46a85
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/204117
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>