skia: Adjust help-msvc-analyzer.patch to unbreak clang-cl build
This patch was originally added in

    commit 52a06992f1404a4b85f99aedd75377fd60a489b9
    Date:   Sat May 11 19:44:21 2024 +0100

        help msvc -analyzer out wrt SkASSERT

and then adjusted for newer Skia versions. While it
is targeted at MSVC, the `defined(_MSC_VER)` check
would also be true for clang-cl on Windows, resulting
in build failures like these:

    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/win/app/WindowsInstance.cxx:22:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/win/gdiimpl.hxx:16:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/gdiimpl.hxx:27:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/utils.hxx:43:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/workdir/UnpackedTarball/skia\tools/window/WindowContext.h:12:
    C:/Users/mwegh/development/git/libreoffice-WORKTREE/workdir/UnpackedTarball/skia\tools/window/DisplayParams.h(96,26): error: call to deleted constructor of 'std::unique_ptr<DisplayParams>'
       96 |         SkASSERT_RELEASE(fDisplayParams);
          |                          ^~~~~~~~~~~~~~
    C:/PROGRA~1/MICROS~1/2022/COMMUN~1/VC/Tools/MSVC/14.44.35207/Include\memory(3475,5): note: 'unique_ptr' has been explicitly marked deleted here
     3475 |     unique_ptr(const unique_ptr&)            = delete;
          |     ^
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/win/app/WindowsInstance.cxx:22:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/win/gdiimpl.hxx:16:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/gdiimpl.hxx:27:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/vcl/inc\skia/utils.hxx:43:
    In file included from C:/Users/mwegh/development/git/libreoffice-WORKTREE/workdir/UnpackedTarball/skia\tools/window/WindowContext.h:12:
    C:/Users/mwegh/development/git/libreoffice-WORKTREE/workdir/UnpackedTarball/skia\tools/window/DisplayParams.h(102,26): error: call to deleted constructor of 'std::unique_ptr<DisplayParams>'
      102 |         SkASSERT_RELEASE(fDisplayParams);
          |                          ^~~~~~~~~~~~~~
    C:/PROGRA~1/MICROS~1/2022/COMMUN~1/VC/Tools/MSVC/14.44.35207/Include\memory(3475,5): note: 'unique_ptr' has been explicitly marked deleted here
     3475 |     unique_ptr(const unique_ptr&)            = delete;
          |     ^

Aditionally check that `__clang__` is not defined, so
the check is still true for MSVC, but no longer
for clang-cl.

Change-Id: Ibe0785d4136f76264f8cea31db3dc297451415a8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202779
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>