Make odk unoapploader C code build with GCC 15.2
With GCC 15.2, compiler produces this error message:

[LOC] top level modules: odk
odk/source/unoapploader/unx/unoapploader.c: In function ‘createCommandName’:
odk/source/unoapploader/unx/unoapploader.c:285:13: error: assignment discards
‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  285 |         sep = strrchr( prgname, SEPARATOR );
      |             ^
cc1: all warnings being treated as errors

By defining sep as "const char*" instead of "char*", the problem goes away.

Change-Id: If1d628dba8bb4ec657b916fa61927b250d3039c3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202942
Tested-by: Jenkins
Reviewed-by: Hossein <hossein@libreoffice.org>