vcl: Merge SvTreeListBox with SvListView base class
Merge the SvListView base class into its only direct
subclass, SvTreeListBox.

Rename SvListView::Clear to SvTreeListBox::Reset to
avoid a name clash with the existing SvTreeListBox::Clear.

Move the call to `m_DataTable.clear();` from the SvListView
dtor to SvTreeListBox::dispose to address this clang plugin
warning/error seen otherwise:

    /home/michi/development/git/libreoffice/vcl/source/treelist/treelistbox.cxx:1615:1: error: VclReferenceBase subclass should have nothing in its destructor but a call to disposeOnce() [loplugin:vclwidgets]
     1615 | SvTreeListBox::~SvTreeListBox()
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1616 | {
          | ~
     1617 |     disposeOnce();
          |     ~~~~~~~~~~~~~~
     1618 |
     1619 |     m_DataTable.clear();
          |     ~~~~~~~~~~~~~~~~~~~~
     1620 | }
          | ~
    1 error generated.

No change in behavior intended. Further simplification
may follow.

Change-Id: Ib94f28c56536fb5c59c26c445e74827bfbbe1228
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201858
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins